### ISSUE TITLE
Help for more specifically Generate

### ISSUE THREAD

**Issue by mingzailao** [kerighan/graph-walker#1]
If such a vertex does not exist (as all the neighbors already belong to the walk), the walk is tracked backwards until an un-visited neighbor is found. this neighbor is added to the walk

How can I implement this ?

**Comment by kerighan** [comment]
You cannot do this using this package, and I suspect that the whole process would be far slower and very demanding in RAM, as it would imply to store all visited nodes for each walk in the graph. You'd be better off implementing a parallel depth first search algorithm.
