### ISSUE TITLE
Walk probability proportional to edge weights? AND error

### ISSUE THREAD

**Issue by eszabo12** [kerighan/graph-walker#10]
I can't find any documentation on this library.

I have a DiGraph with weighted edges and I want the random walk to walk proportional to the non-uniform edge weights. Is this taken into account? 

Edit: I am also getting this error

`TypeError: random_walks() got an unexpected keyword argument 'start_node'`
Python3.10

graph-walker Version: 1.0.6

**Comment by benelot** [comment]
The parameter is now called start_nodes. The other part I cannot answer unfortunately. I think you will have to look into the code.

**Comment by kerighan** [comment]
Yes, the weights of the edges are linearly proportional to the probability of following an edge.
