### ISSUE TITLE
running example error

### ISSUE THREAD

**Issue by morningphase** [kerighan/graph-walker#2]
the error info is：
/usr/include/c++/10/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = float; _Alloc = std::allocator<float>; std::vector<_Tp, _Alloc>::reference = float&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.

**Comment by kerighan** [comment]
Please provide a code example so that I can reproduce the issue.
