### ISSUE TITLE
Did some push break the package? 

### ISSUE THREAD

**Issue by josh-ashkinaze** [kerighan/graph-walker#7]
```
import walker
import networkx as nx
G = nx.random_partition_graph([10] * 15, .01, .001)

X = walker.random_walks(G, n_walks=50, walk_len=25)

```
Returns `AttributeError: module 'walker' has no attribute 'random_walks'`

**Comment by erik-hormann** [comment]
I had the same problem but I solved it. Apparently there is another walker package that does something completely different. I was using pycharm and despite pip-ing the correct walker, I somehow ended up with the wrong package. I would say to double check your packages :)
